project:
  type: book
  output-dir: docs

book:
  title: "Workshop Bash 2024"
  author: "Evelia Coss y Aaron Espinosa Jaime"
  date: "12/10/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - requisitos.qmd
    - intro.qmd
    - Bash.qmd
    - Rnaseq_intro.qmd
    - Parte2A.qmd
    - Parte2B.qmd
    - Parte3A.qmd
    - Parte3B.qmd
    - Parte4A.qmd
    - Parte4B.qmd
    - Parte5.qmd
    - Parte6.qmd
    - Parte7.qmd
    - Parte8.qmd
  # Information
  repo-url: https://github.com/ISCB-RSG-MEXICO/Workshop_Bash2024 # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "rsgMexico.png" # icono de la pagina en pestana

format:
  html:
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    freeze: false  # Desactivar congelamiento

editor: visual

