project:
  type: book
  output-dir: docs

book:
  title: "Workshop Bash 2024"
  author: "Evelia Coss y Aaron Espinosa Jaime"
  date: "12/10/2024"
  page-navigation: true
  chapters:
    - index.qmd
    - part: "**Section 1** - Introducci贸n a Bash"
      chapters: 
      - BetterLab.qmd
      - intro.qmd
      - Bash.qmd
    - part: "**Section 2** - Manejo y redirecci贸n de datos"
      chapters: 
      - Rnaseq_intro.qmd
      - Parte2A.qmd
      - Parte2B.qmd
    - part: "**Section 3** - Edici贸n de archivos"
      chapters: 
      - Parte3A.qmd
      - Parte3B.qmd
    - part: "**Section 4** - Manejo y redirecci贸n de datos"
      chapters: 
      - BuenasPracticas.qmd
      - Parte4A.qmd
      - Parte4B.qmd
    - part: "**Section 5** - Condicionales"
      chapters: 
      - Parte5.qmd
      - Parte6.qmd
    - part: "**Section 6** - Bucles (for loops)"
      chapters: 
      - Parte7.qmd
    - Parte8.qmd
  # Information
  repo-url: https://github.com/ISCB-RSG-MEXICO/Workshop_Bash2024 # link de Github
  sharing: [twitter, facebook, linkedin]
  favicon: "rsgMexico.png" # icono de la pagina en pestana

format:
  html:
    toc-depth: 4
    number-depth: 3
  # Boton para cambiar tema de oscuro a claro
    theme:
      light: cosmo
      dark: darkly
    code-fold: show # Ocultar codigo
    code-copy: true # Copy button
    code-wrap: true
    message: false
    warning: false
    fig-height: 8 # Proporcion de figuras
    fig-width: 8
    fig-align: "center"
    freeze: false  # Desactivar congelamiento
    grid: 
      body-width: 1200px
      sidebar-width: 250px
      margin-width: 200px
      gutter-width: 0.8em
    fontsize: 14pt

editor: visual

